{ config, inputs, ... }:
{
  disabledModules = [
    # Stylix's kmscon module is incompatible with nixpkgs 26.05.
    # TODO: drop once upstream stylix release-26.05 ships the fix.
    "${inputs.stylix}/modules/kmscon/nixos.nix"
  ];

  imports = [
    ./hardware.nix
    ../../modules/options.nix
    ../../profiles/core/nixos.nix
    ../../profiles/shell/nixos.nix
    ../../profiles/theming/nixos.nix
    ../../profiles/desktop/niri/nixos.nix
    ../../profiles/desktop/gnome/nixos.nix
    ../../profiles/gaming/nixos.nix
    ../../profiles/storage/nixos.nix
    ../../profiles/ai/nixos.nix
    ../../profiles/local-ai/nixos.nix
    ../../users/nixos.nix
  ];

  # ═══════════════════════════════════════════════════════════════════════════
  #                          ⮞⮞  EDIT BELOW  ⮜⮜
  #     This is the ONE file a new user needs to touch on a fresh machine.
  #     Hardware-specific UUIDs (root, boot) live in ./hardware.nix and are
  #     auto-generated by `nixos-generate-config` per machine.
  # ═══════════════════════════════════════════════════════════════════════════
  mySystem = {
    # ── Identity ─────────────────────────────────────────────────────────────
    user = {
      name = "dillen";
      fullName = "dillen";
      extraGroups = [
        "networkmanager"
        "wheel"
      ];
    };
    hostname = "nixos";
    timezone = "Europe/Berlin";
    locale = {
      main = "en_US.UTF-8";
      regional = "de_DE.UTF-8";
      consoleKeymap = "de-latin1-nodeadkeys";
      xkbLayout = "de";
      xkbVariant = "nodeadkeys";
    };

    # ── Kernel ───────────────────────────────────────────────────────────────
    kernel = "default"; # "default" | "latest" | "zen"

    # ── Desktop ──────────────────────────────────────────────────────────────
    desktop = "niri"; # "niri" | "gnome"

    # ── Standalone (non-NixOS machine) ───────────────────────────────────────
    # Exposes `homeConfigurations.<user>` built from this same file. Only
    # identity differs per machine; theming/locale/toggles are inherited above.
    # Apply: home-manager switch --flake .#<user>
    standalone = {
      enable = true;
      user = "niklas";
      gpu = "mesa"; # "mesa" (Intel/AMD) | "nvidia" (proprietary driver) — picks the nixGL wrapper
      flakePath = "~/Documents/nix"; # where this repo lives on the machine (used by the `rebuild` alias)
      # Output switching (kanshi, niri only). Ordered list of profiles; kanshi
      # applies the first whose outputs are ALL connected, so list multi-monitor
      # docks before the bare-laptop fallback. Disable the panel to show only
      # externals. Connector names from `niri msg outputs`.
      monitors = {
        enable = true;
        fallbackAllOn = true; # if no profile matches, enable all outputs (extended; not true mirror)
        profiles = [
          {
            name = "docked";
            outputs = [
              {
                connector = "eDP-1";
                status = "disable";
              }
              {
                connector = "HDMI-A-1";
                status = "enable";
                position = "0,0";
                scale = 1.0;
              }
            ];
          }
          {
            name = "mobile";
            outputs = [
              {
                connector = "eDP-1";
                status = "enable";
                position = "0,0";
                scale = 1.25;
              }
            ];
          }
        ];
      };
    };

    # ── Profiles (toggle features) ───────────────────────────────────────────
    ai.enable = false; # Claude Code, rtk, codegraph, nix-ld

    theming = {
      enable = true;
      # ┌─ Available schemes (pkgs.base16-schemes) ───────────────────────────┐
      # │ scheme name                       │ polarity                        │
      # ├───────────────────────────────────┼─────────────────────────────────┤
      # │ catppuccin-mocha                  │ dark                            │
      # │ catppuccin-macchiato              │ dark                            │
      # │ catppuccin-frappe                 │ dark                            │
      # │ catppuccin-latte                  │ light                           │
      # │ gruvbox-dark-hard                 │ dark                            │
      # │ gruvbox-dark-medium               │ dark                            │
      # │ gruvbox-dark-soft                 │ dark                            │
      # │ gruvbox-material-dark-hard        │ dark                            │
      # │ gruvbox-light-hard                │ light                           │
      # │ gruvbox-light-medium              │ light                           │
      # │ nord                              │ dark                            │
      # │ nord-light                        │ light                           │
      # │ dracula                           │ dark                            │
      # │ tokyo-night-dark                  │ dark                            │
      # │ tokyo-night-storm                 │ dark                            │
      # │ tokyo-night-moon                  │ dark                            │
      # │ tokyo-night-light                 │ light                           │
      # │ rose-pine                         │ dark                            │
      # │ rose-pine-moon                    │ dark                            │
      # │ rose-pine-dawn                    │ light                           │
      # │ kanagawa                          │ dark                            │
      # │ kanagawa-dragon                   │ dark                            │
      # │ everforest                        │ dark                            │
      # │ everforest-dark-hard              │ dark                            │
      # │ everforest-dark-medium            │ dark                            │
      # │ everforest-dark-soft              │ dark                            │
      # │ onedark                           │ dark                            │
      # │ onedark-dark                      │ dark                            │
      # │ ayu-dark                          │ dark                            │
      # │ ayu-mirage                        │ dark                            │
      # │ ayu-light                         │ light                           │
      # │ solarized-dark                    │ dark                            │
      # │ solarized-light                   │ light                           │
      # │ material                          │ dark                            │
      # │ material-darker                   │ dark                            │
      # │ material-palenight                │ dark                            │
      # │ material-lighter                  │ light                           │
      # │ monokai                           │ dark                            │
      # │ gotham                            │ dark                            │
      # └───────────────────────────────────┴─────────────────────────────────┘
      # Full list: ls ${pkgs.base16-schemes}/share/themes/
      scheme = "monokai";
      polarity = "dark"; # "dark" | "light" | "either" — must match scheme
      # wallpaper = ../../wallpaper.png;
    };

    gaming = {
      enable = false;
      gamescope = {
        width = 3440;
        height = 1440;
      };
    };

    localAi = {
      enable = false;
      rocmGfx = "11.0.0"; # 7900 XTX=11.0.0, 7800/7700 XT=11.0.1, 6900 XT=10.3.0
    };

    storage.automount = {
      enable = false;
      mounts = [
        {
          path = "Grab";
          uuid = "b7139bdc-09fd-4008-9ab2-243eb5aacc05";
        }
        {
          path = "Games_Part";
          uuid = "9171c17f-e154-41f4-87ac-69a020fbebbd";
        }
      ];
    };
  };
  # ═══════════════════════════════════════════════════════════════════════════

  home-manager = {
    useGlobalPkgs = true;
    useUserPackages = true;
    backupFileExtension = "hm-backup";
    extraSpecialArgs = { inherit inputs; };
    users.${config.mySystem.user.name} = import ../../users/home.nix;
  };
}
